function sdivGgrad_v = divGgrad_v_(x,y)
%DIVGGRAD_V_
%    SDIVGGRAD_V = DIVGGRAD_V_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:07

sdivGgrad_v = 5.511111111111111e2;
