function sdivGgrad_u = divGgrad_u_(x,y)
%DIVGGRAD_U_
%    SDIVGGRAD_U = DIVGGRAD_U_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:06

sdivGgrad_u = 1.102222222222222e3;
