function sL_SP = L_SP_(x,y)
%L_SP_
%    SL_SP = L_SP_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:53:57

sL_SP = x.^2.*3.333333333333333e-7+y.^2.*2.222222222222222e-7+1.0;
