function [nx,ny] = normal_phi2_(x,y)
%NORMAL_PHI2_
%    [NX,NY] = NORMAL_PHI2_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:18

t2 = y+3.603e3;
t3 = x.^2;
t9 = y.*2.0;
t4 = t9+7.206e3;
t5 = t2.^2;
t6 = t3+t5;
t7 = 1.0./t6;
t8 = t3.*t7;
t10 = t4.^2;
t11 = t7.*t10.*(1.0./4.0);
t12 = t8+t11;
t13 = 1.0./sqrt(t12);
t14 = 1.0./sqrt(t6);
nx = t13.*t14.*x;
if nargout > 1
    ny = t4.*t13.*t14.*(1.0./2.0);
end
