function [nx,ny] = normal_phi1_(x,y)
%NORMAL_PHI1_
%    [NX,NY] = NORMAL_PHI1_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:17

nx = 0.0;
if nargout > 1
    ny = 1.0;
end
