function sphi2 = phi2_(x,y)
%PHI2_
%    SPHI2 = PHI2_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:53:58

t2 = y+3.603e3;
sphi2 = sqrt(t2.^2+x.^2)-5.0e2;
