function ssig = sig_(x,y)
%SIG_
%    SSIG = SIG_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:53:56

ssig = x.^2.*1.111111111111111e-7+y.^2.*1.111111111111111e-7+1.0;
