function ssigmanu1 = sigmanu1_(x,y)
%SIGMANU1_
%    SSIGMANU1 = SIGMANU1_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:12

ssigmanu1 = x.*5.511111111111111e2+y.*6.888888888888889e2;
