function ssigmanv2 = sigmanv2_(x,y)
%SIGMANV2_
%    SSIGMANV2 = SIGMANV2_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:14

t2 = y+3.603e3;
t3 = x.^2;
t9 = y.*2.0;
t4 = t9+7.206e3;
t5 = t2.^2;
t6 = t3+t5;
t7 = 1.0./t6;
t8 = t3.*t7;
t10 = t4.^2;
t11 = t7.*t10.*(1.0./4.0);
t12 = t8+t11;
t13 = 1.0./sqrt(t12);
t14 = 1.0./sqrt(t6);
t15 = y.^2;
ssigmanv2 = t4.*t13.*t14.*(t3.*4.444444444444444e-7+t15.*3.333333333333333e-7+x.*6.879244444444445e5+y.*6.877866666666667e5-(t3.*2.755555555555556e2+t15.*2.755555555555556e2+x.*y.*2.755555555555556e2)./x+2.0).*(-1.0./2.0)+t13.*t14.*x.*(x.*5.511111111111111e2+y.*6.888888888888889e2);
