function ssigmanu2 = sigmanu2_(x,y)
%SIGMANU2_
%    SSIGMANU2 = SIGMANU2_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:13

t2 = y+3.603e3;
t3 = x.^2;
t10 = y.*2.0;
t4 = t10+7.206e3;
t5 = t2.^2;
t6 = t3+t5;
t7 = 1.0./t6;
t8 = y.^2;
t9 = t3.*t7;
t11 = t4.^2;
t12 = t7.*t11.*(1.0./4.0);
t13 = t9+t12;
t14 = 1.0./sqrt(t13);
t15 = 1.0./sqrt(t6);
ssigmanu2 = -t14.*t15.*x.*(t3.*4.444444444444444e-7+t8.*3.333333333333333e-7+x.*6.870977777777778e5+y.*6.877866666666667e5-(t3.*2.755555555555556e2+t8.*2.755555555555556e2+x.*y.*2.755555555555556e2)./x+2.0)+t4.*t14.*t15.*(x.*5.511111111111111e2+y.*6.888888888888889e2).*(1.0./2.0);
