function ssolgpy = solgpy_(x,y)
%SOLGPY_
%    SSOLGPY = SOLGPY_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:04

ssolgpy = y.*6.666666666666667e-7;
