function ssolp = solp_(x,y)
%SOLP_
%    SSOLP = SOLP_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:53:59

ssolp = x.^2.*4.444444444444444e-7+y.^2.*3.333333333333333e-7+2.0;
