function ssolsp = solsp_(x,y)
%SOLSP_
%    SSOLSP = SOLSP_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:00

ssolsp = x.^2.*3.333333333333333e-7+y.^2.*3.333333333333333e-7;
