function ssolspx = solspx_(x,y)
%SOLSPX_
%    SSOLSPX = SOLSPX_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:04

ssolspx = x.*6.666666666666667e-7;
