function ssolspy = solspy_(x,y)
%SOLSPY_
%    SSOLSPY = SOLSPY_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:05

ssolspy = y.*6.666666666666667e-7;
