function ssolT = solT_(x,y)
%SOLT_
%    SSOLT = SOLT_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:53:59

ssolT = x.*3.333333333333333e-4+y.*3.333333333333333e-4;
