function ssoluy = soluy_(x,y)
%SOLUY_
%    SSOLUY = SOLUY_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:03

ssoluy = x.*2.222222222222222e-7+y.*4.444444444444444e-7;
