function ssolu = solu_(x,y)
%SOLU_
%    SSOLU = SOLU_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:23

ssolu = x.*y.*2.222222222222222e-7+x.^2.*2.222222222222222e-7+y.^2.*2.222222222222222e-7;
