function ssolux = solux_(x,y)
%SOLUX_
%    SSOLUX = SOLUX_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:03

ssolux = x.*4.444444444444444e-7+y.*2.222222222222222e-7;
