function ssolv = solv_(x,y)
%SOLV_
%    SSOLV = SOLV_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:53:55

ssolv = x.*y.*1.111111111111111e-7+x.^2.*1.111111111111111e-7+y.^2.*1.111111111111111e-7;
