function ssolvx = solvx_(x,y)
%SOLVX_
%    SSOLVX = SOLVX_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:03

ssolvx = x.*2.222222222222222e-7+y.*1.111111111111111e-7;
