function ssolvy = solvy_(x,y)
%SOLVY_
%    SSOLVY = SOLVY_(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:03

ssolvy = x.*1.111111111111111e-7+y.*2.222222222222222e-7;
