function out1 = xt1_(xi)
%XT1_
%    OUT1 = XT1_(XI)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Apr-2021 14:54:17

t2 = xi.^2;
t3 = t2-1.0;
out1 = t2.*1.0./t3.^2.*6.0e3-3.0e3./t3;
