function sxt2 = xt2_(sx)
%XT2_
%    SXT2 = XT2_(SX)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    21-Jan-2013 17:22:02

t30 = sx.^2;
t31 = t30-1.0;
sxt2 = sx.*1.0./t31.^2.*6.0-sx.*t30.*1.0./t31.^3.*8.0;
